### ISSUE TITLE
Add code linter workflow

### ISSUE THREAD

**Issue by pogzyb** [pogzyb/asyncwhois#39]
Add black code-style linter that runs on each PR

- run the black formatter on the code base
- create linter.yml under .github/workflows

**Comment by rahulXs** [comment]
Hey @pogzyb, Could you please tell me if the linter workflow using black should only detect the issue or it should also fix the code style violations automatically?
Also taking reference to the `build-and-test.yml` workflow, Is it okay to use only a single runner for the linter workflow instead of matrix of agents kind because the black formatter would run the same way on all kind of runners?
Please let me know. Thanks.

**Comment by pogzyb** [comment]
> Hey @pogzyb, Could you please tell me if the linter workflow using black should only detect the issue or it should also fix the code style violations automatically? Also taking reference to the `build-and-test.yml` workflow, Is it okay to use only a single runner for the linter workflow instead of matrix of agents kind because the black formatter would run the same way on all kind of runners? Please let me know. Thanks.

Hi @rahulXs - Thanks for taking this on.

1. If you can configure it to automatically fix formatting issues that would be awesome, but not a requirement, as long as it fails for lint issues is good for now. 
2. Yes, a single runner is preferred for this workflow.

**Comment by rahulXs** [comment]
@pogzyb - Thanks for the reply. I would work on it and raise the PR by tomorrow.
