### ISSUE TITLE
Cache data.iana.org/rdap/dns.json for a configurable amount of time

### ISSUE THREAD

**Issue by koromodako** [pogzyb/asyncwhois#73]
Hello,

I noticed that performing several RDAP searches results in downloading `data.iana.org/rdap/dns.json` each time a RDAP search is made. 

In your opinion, can this file be cached for a configurable amount of time instead ? Or maybe I missed something that prevents implementing this behavior. 

Thank you

**Comment by pogzyb** [comment]
Hi,

Thanks for opening this issue. You're right - this is currently a gap in how this library implements RDAP. 

The underlying [whodap](https://github.com/pogzyb/whodap) library does provide caching of this initial download if a `whodap.DNSClient` is created and reused, but the way in which asyncwhois uses whodap for RDAP is only via the "convenience" functions and not the reusable client pattern. Overall, it's definitely possible to implement this it just hasn't been done yet. A couple of other people have also asked about for this in side conversations, so I'll prioritize this and try to get something implemented soon. 

Also, instead of a "configurable amount of time" I was thinking to make the `asyncwhois.DomainLookup` client available and have the data cached throughout the lifetime of the client (i.e. until the script ends or the client is de-allocated). Does that work for your use-case or would you prefer to have it time-based?

pseudo-code:
```
client = asyncwhois.DomainLookup(<some config params>)

result = client.rdap("google.com")  # iana json should be cached after executing
result = client.rdap("google.buzz")  # additional calls use cache
result = await client.aio_rdap("google.app")
```

Let me know what you think - I'll keep you updated!

**Comment by koromodako** [comment]
Have the data cached throughout the lifetime of the client seems to be a good option indeed. :+1:

**Comment by pogzyb** [comment]
The latest release 1.1.0 now handles this. Here's some example code:
```
import asyncwhois

client = asyncwhois.DomainClient()

for domain in ["google.com", "tesla.coffee", "mango.beer"]:
    text, parsed = client.rdap(domain)  # client methods, `.whois` and `.rdap`, return tuples now 
```
Hope this helps!
