### ISSUE TITLE
Add Contact Emails To Default Parsed Output

### ISSUE THREAD

**Issue by uBadRequest** [pogzyb/asyncwhois#9]
I noticed that contact emails aren't being parsed by default and seems to be commented out in the code, any reasons why?

Should I fork and add email or was there a problem?

**Comment by pogzyb** [comment]
No, you should be able to uncomment or add parsers for emails without a problem. This package started out as a small piece of a larger security project of mine where I really only needed to reliably parse dates and address information, so I forewent adding parsers for contact fields at the time.

I'll admit I'm probably more focused on getting wider TLD coverage rather than fully supporting the contact stuff right now; so yes, please go ahead and fork for your own needs.

Good luck!
